/*
  This file is GENERATED by Claude during Step 05 — Render.
  Do not edit manually. Claude reads resources/brand.md and
  resources/design-system.md to produce this file for each carousel.

  This template shows the expected structure. Delete and regenerate
  for your first carousel.

  Pattern: Define brand constants at the top, then one function per slide.
*/

import { Card } from './components/Card'

// Brand constants — Claude fills these from brand.md during Step 05
const accent = '#YOUR_ACCENT_COLOR'        // e.g., '#E63946', '#2563EB', '#059669'
const accentTextShadow = '0 1px 4px rgba(0,0,0,0.3)'
const accentFont = "'Your Accent Font', Georgia, serif"  // e.g., "'Playfair Display', Georgia, serif"

function Slide({ children, bg }: { children: React.ReactNode; bg: string }) {
  return (
    <div id="carousel-slide" style={{
      width: 1080, height: 1350, position: 'relative', overflow: 'hidden', background: '#000',
    }}>
      <img src={bg} alt="" style={{
        position: 'absolute', inset: 0, width: '100%', height: '100%',
        objectFit: 'cover',
      }} />
      <div style={{
        position: 'absolute', inset: 0,
        background: 'rgba(0, 0, 0, 0.25)',
      }} />
      <div style={{
        position: 'relative', zIndex: 10, width: '100%', height: '100%',
        display: 'flex', flexDirection: 'column',
        // Page padding — Claude sets this from brand.md
        padding: '48px 40px',
      }}>
        {children}
      </div>
    </div>
  )
}

/* ---- SLIDE 1: Hook (Pattern A) ---- */
function Slide1() {
  return (
    <Slide bg="/bg-01.jpg">
      <div style={{ flex: 1, display: 'flex', flexDirection: 'column', justifyContent: 'center', alignItems: 'center', gap: 28 }}>
        <Card radius={24} style={{ width: '100%' }}>
          <div style={{ padding: '44px 40px', textAlign: 'center' }}>
            <h1 style={{
              color: '#fff', fontSize: 74, fontWeight: 700,
              lineHeight: 1.15, letterSpacing: '-2.5px',
            }}>
              Your Hook{' '}
              <span style={{
                color: accent, textShadow: accentTextShadow,
                fontFamily: accentFont, fontStyle: 'italic', fontWeight: 400,
              }}>
                Headline
              </span>
            </h1>
          </div>
        </Card>

        <Card radius={24} style={{ width: '100%' }}>
          <div style={{ padding: '24px 40px', textAlign: 'center' }}>
            <p style={{
              color: 'rgba(255,255,255,0.85)', fontSize: 42, fontWeight: 300,
              lineHeight: 1.4,
            }}>
              Supporting text goes here.
            </p>
          </div>
        </Card>

        <Card radius={50} style={{ alignSelf: 'center' }}>
          <div style={{ padding: '16px 40px', textAlign: 'center' }}>
            <p style={{
              color: 'rgba(255,255,255,0.85)', fontSize: 32, fontWeight: 500,
            }}>
              Swipe to learn more →
            </p>
          </div>
        </Card>
      </div>
    </Slide>
  )
}

/* ---- SLIDE 2: Save CTA (Pattern E) ---- */
function Slide2() {
  return (
    <Slide bg="/bg-02.jpg">
      <div style={{ flex: 1, display: 'flex', flexDirection: 'column', justifyContent: 'center', alignItems: 'center' }}>
        <div style={{ position: 'relative' }}>
          <Card radius={50} style={{ width: '100%' }}>
            <div style={{ padding: '44px 48px', textAlign: 'center' }}>
              <p style={{
                color: '#fff', fontSize: 48, fontWeight: 700,
                lineHeight: 1.25, letterSpacing: '-1.5px',
              }}>
                Save this for later
              </p>
            </div>
          </Card>
          {/* Bookmark badge — overlapping top-right */}
          <div style={{ position: 'absolute', top: -20, right: -10 }}>
            <Card radius={999} width={88} height={88} center>
              <img src="/icons/bookmark.svg" alt="" style={{ width: 36, height: 36 }} />
            </Card>
          </div>
        </div>
      </div>
    </Slide>
  )
}

function App() {
  return (
    <div style={{
      display: 'flex', flexDirection: 'column', alignItems: 'center',
      gap: 60, padding: 40, background: '#111', minHeight: '100vh',
    }}>
      <Slide1 />
      <Slide2 />
    </div>
  )
}

export default App
